final Map<String, String> languageUS = {
      'totalBalanceText': 'your total balance',
      'chooseCryptocurrency': 'Choose a cryptocurrency',
      'swapText': 'Swap',
      'createWalletButtonText': 'Create wallet',
      'importWalletButtonText': 'Import wallet',
      'createWalletScreenText': 'Save mnemonic in a safe place',
      'copySeedShowToast': 'Mnemonic copied',
      'backText': 'Back',
      'fillAllFieldsShowToast': 'Fill in all the fields',
      'signInText': 'Sign In',
      'enterMnemonicText': 'Enter mnemonic',
      'pasteText': 'paste',
      'depositText': 'Receive',
      'sendTokensText': 'Send',
      'assetsText': 'Assets',
      'scanQrDestinationText': 'Scan the recipients QR code',
      'warningTextWith': 'Attention! send to this address only tokens running on the solana blockchain',
      'inputAddressWith': 'Recipient address',
      'inputSumText': 'Input amount',
      'enterBankCardNumber': 'Enter bank card number',
      'sendText': 'Send',
      'closeText': 'Close',
      'exitText': 'Exit',
      'confirmExitText': 'Are you sure you want to log out?',
      'yesText': 'Yes',
      'noText': 'No',
      'warningSaveSeedShowToast': '* Save the Seed-phrase in a safe place',
      'saveText': 'Save',
      'changeLanguage': 'Change language',
      'languageText': 'Language',
      'privateKeyText': 'Private key',
      'earn': 'Earn',
      'english': 'English',
      'russia': 'Russia',
      'turkish': 'Turkish',
      'empty': 'Empty',
      'maxSupplyText': 'Max supply',
      'sellPriceText': 'Sell price',
      'buyText': 'Buy',
      'sellText': 'Sell',
      'exclusivelyForNaxarHolders': 'Exclusively for Boxch holders',
      'soonText': 'Soon',
      'referralText': 'Referral Program',
      'referralSubtitleText': 'Invite friends and get rewarded in cryptocurrency',
      'earnText': 'Main',
      'sendFarmTokensText': 'Send tokens to the farm and get rewarded',
      'createText': 'Create',
      'claimText': 'Claim',
      'closeAccount': "Close account",
      'burnAndCloseAccountText': "Burn & Close",
      'searchCryptocurrency': "Search",
      'balanceText': "balance:",
      'buySellText': 'Buy & Sell',
      'likingBoxchText': "Liking boxch?",
      'needHelpText': "Need help?",
      'privacyPolicyText': "Privacy policy",
      'changeTheme': 'Change theme',

      'goodMorning': 'Good morning,',
      'goodAfternoon': 'Good afternoon,',
      'goodEvening': 'Good evening,',
      'goodNight': 'Good night,',

      'quickSend': 'Quick send',
      'viewAll': 'View all',

      'settingsText': 'Settings',
      'iGiveText': 'I give',
      'iGetText': 'I get',
      'continueText': 'Continue',
      'searchTokenText': 'Search token',
      'сonfirmSwapText': 'Confirm Swap',
      'slippageText': 'Slippage:',
      'priceImpctText': 'Price Impct:',
      'tryReducingText': 'Try reducing your trade size for a better rate',
      'confirmText': 'Confirm',
      'onlyAcceptText': 'This address only accepts tokens from',
      'swipeToSendText': 'swipe to send',
      'normalText': 'Normal',

      'buySellDev': 'Buying and selling with the card is in development',
      'plBuySell': 'Please use one of the third-party providers available in your country:',

      'loginTermsText': 'I read this and agree ',
      'changePasswordText': 'Change password',
      'inputPasswordText': 'Input password',
      'resetPasswordText': 'Forgot password'
    };