final Map<String, String> languageUS = {
      'totalBalanceText': 'Total balance',
      'chooseCryptocurrency': 'Choose a cryptocurrency',
      'createWalletButtonText': 'Create new wallet',
      'importWalletButtonText': 'I already have a wallet',
      'createWalletScreenText': 'Save mnemonic in a safe place',
      'copySeedShowToast': 'Mnemonic copied',
      'backText': 'Back',
      'fillAllFieldsShowToast': 'Fill in all the fields',
      'signInText': 'Sign In',
      'enterMnemonicText': 'Mnemonic',
      'enterPrivateKeyText': 'Private key',
      'pasteText': 'paste',
      'depositText': 'Receive',
      'sendTokensText': 'Send',
      'tokensText': 'Tokens',
      'inputAddressWith': 'Recipient address',
      'inputSumText': 'Input amount',
      'closeText': 'Close',
      'exitText': 'Exit',
      'confirmExitText': 'Are you sure you want to log out?',
      'yesText': 'Yes',
      'noText': 'No',
      'saveText': 'Save',
      'changeLanguage': 'Change language',
      'languageText': 'Language',
      'privateKeyText': 'Private key',
      'earnText': 'Earn',
      'english': 'English',
      'empty': 'Empty',
      'maxSupplyText': 'Max supply',
      'sellPriceText': 'Sell price',
      'buyText': 'Buy',
      'sellText': 'Sell',
      'closeAccount': "Close account",
      'burnAndCloseAccountText': "Burn & Close",
      'searchCryptocurrency': "Search",
      'balanceText': "balance:",
      'buySellText': 'Buy & Sell',
      'likingBoxchText': "Liking boxch?",
      'needHelpText': "Need help?",
      'privacyPolicyText': "Privacy policy",
      'changeTheme': 'Change theme',
      'biometricAuthText': 'Biometric auth',

      'goodMorning': 'Good morning,',
      'goodAfternoon': 'Good afternoon,',
      'goodEvening': 'Good evening,',
      'goodNight': 'Good night,',

      'quickSend': 'Quick send',
      'viewAll': 'View all',

      'settingsText': 'Settings',
      'swipeToSendText': 'swipe to send',

      'buySellDev': 'Buying and selling with the card is in development',
      'plBuySell': 'Please use one of the third-party providers available in your country:',

      'loginTermsText': 'I read this and agree ',
      'changePasswordText': 'Change password',
      'inputPasswordText': 'Input password',
      'resetPasswordText': 'Forgot password'
    };