final Map<String, String> languageRU = {
      'totalBalanceText': 'ваш общий баланс',
      'chooseCryptocurrency': 'Выберите криптовалюту',
      'swapText': 'свап',
      'swapTokensText': 'Конвертация между двумя токенами',
      'createWalletButtonText': 'Создать кошелек',
      'importWalletButtonText': 'Импортировать кошелек',
      'createWalletScreenText': 'Сохраните мнемонику в надежном месте',
      'copySeedShowToast': 'Мнемоника скопирована',
      'backText': 'Назад',
      'fillAllFieldsShowToast': 'Заполните все поля',
      'signInText': 'Войти',
      'enterMnemonicText': 'Введите мнемонику',
      'pasteText': 'вставить',
      'depositText': 'получить',
      'sendTokensText': 'Отправить',
      'launchpadText': 'Лаунчпад',
      'assetsText': 'активы',
      'scanQrDestinationText': 'Отсканируйте qr-код получателя',
      'warningTextWith': 'Внимание! Отправляйте на этот адрес только токены, работающие на блокчейне Solana',
      'inputAddressWith': 'адрес получателя',
      'inputSumText': 'Введите сумму',
      'sendText': 'отправить',
      'developerText': 'Разработчик',
      'closeText': 'Закрыть',
      'exitText': 'Выйти',
      'confirmExitText': 'Вы уверены что хотите выйти?',
      'yesText': 'Да',
      'noText': 'Нет',
      'yourSeedText': 'Ваша ',
      'warningSaveSeedShowToast': '* Сохраните seed-фразу в надежном месте',
      'saveText': 'Сохранить',
      'changeLanguage': 'изменить язык',
      'languageText': 'Язык',
      'privateKeyText': 'Приватный ключ',
      'earn': 'Заработать',
      'english': 'Английский',
      'russia': 'Русский',
      'turkish': 'Турецкий',
      'noRunningProjects': 'В настоящее время нет запущенных проектов',
      'closedText': 'Завершенные',
      'empty': 'пусто',
      'collectedText': 'Собрано: ',
      'moreText': 'Участвовать',
      'maxSupplyText': 'Макс. предложение',
      'sellPriceText': 'Цена продажи',
      'vestingText': 'Наделение правами',
      'detailsText': 'Детали IDO',
      'buyText': 'Купить',
      'sellText': 'Продать',
      'startupText': 'запуск через',
      'exclusivelyForNaxarHolders': 'Исключительно для владельцев Boxch',
      'soonText': 'Скоро',
      'referralText': 'Реферальная программа',
      'referralSubtitleText': 'Приглашайте друзей и получайте вознаграждение в криптовалюте',
      'sendFarmTokensText': 'Отправляйте токены на ферму и получайте вознаграждение',
      'createText': 'Создать',
      'claimText': 'Отозвать',
      'closeAccount': "Закрыть аккаунт",
      'burnAndCloseAccountText': "Сжечь и закрыть",
      'searchCryptocurrency': "Поиск",
      'balanceText': "баланс:",
      'buySellText': 'купить & продать',
      'likingBoxchText': "Нравится бохч?",
      'needHelpText': "Нужна помощь?",
      'privacyPolicyText': "Политика конфиденциальности",
      'changeTheme': 'изменить тему',

      'goodMorning': 'доброе утро,',
      'goodAfternoon': 'добрый день,',
      'goodEvening': 'добрый вечер,',
      'goodNight': 'доброй ночи,',

      'quickSend': 'быстрая отправка',
      'viewAll': 'посмотреть все',

      'blockchainConnectivity': 'подключение к блокчейну ...',
      'settingsText': 'настройки',
      'iGiveText': 'Отдаю',
      'iGetText': 'Получаю',
      'continueText': 'Продолжить',
      'searchTokenText': 'поиск токена',
      'сonfirmSwapText': 'Подтвердить Свап',
      'slippageText': 'Проскальзывание:',
      'priceImpctText': 'Влияние на цену:',
      'tryReducingText': 'Попробуйте уменьшить размер сделки для получения более выгодной ставки',
      'confirmText': 'Подтвердить',
      'onlyAcceptText': 'Этот адрес принимает токены только из',
      'swipeToSendText': 'свайпните, чтобы отправить',
      'normalText': 'Нормально',

      'buySellDev': 'Покупка и продажа с помощью карты находится в разработке',
      'plBuySell': 'Пожалуйста, используйте одного из сторонних провайдеров, доступных в вашей стране:',

      'loginTermsText': 'Я прочитал это и согласен ',
      'changePasswordText': 'изменить пароль',
      'inputPasswordText': 'Введите пароль',
      'resetPasswordText': 'Забыл пароль'
    };