name: boxch
version: 2.1.1
description: Application for SOL and SPL tokens Solana Blockchain


environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.0.0
  http: ^0.13.4
  mobile_scanner: ^2.0.0
  solana: ^0.28.1
  url_launcher: ^6.1.2
  hex: ^0.2.0
  countup: ^0.1.4
  flutter_bloc: ^8.0.1
  hive: ^2.2.1
  oktoast: ^3.2.0
  animated_background: ^2.0.0
  flutter_svg: ^1.1.6
  easy_localization: ^3.0.1
  webview_flutter: ^3.0.4
  get: ^4.6.3
  onesignal_flutter: ^3.3.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  iconsax: ^0.0.8
  dropdown_button2: ^1.8.9
  slide_to_act: ^2.0.1
  shimmer_animation: ^2.1.0
  favicon: ^1.1.1
  # solana_wallet_adapter: ^0.0.4+1


  image_picker: ^0.8.6
  # flutter_image_compress: ^1.1.3
  
  #  flutter_vibrate: ^1.3.0
  #  chart_sparkline: ^1.0.11


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.14 #flutter pub run flutter_native_splash:create
  #flutter_launcher_icons: ^0.11.0 #flutter pub run flutter_launcher_icons
  hive_generator: ^2.0.0
  build_runner: ^2.3.2 #dart run build_runner build

  
  # firebase_dynamic_links: ^4.1.1

  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/boxch_logo.png"


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/blockchains/



flutter_native_splash:
  color: "#121A23"
  image: "assets/images/splash_screen.png"
  

